# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: An Ordinary Life
subtitle: 这是一个只属于我的小角落
author: Mr.Li
language: zh-CN
timezone:


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite-url      # Note: don't forget to modify the CNAME file to your url
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# CDN Setting
## Docs: https://www.jsdelivr.com/?docs=gh
## If Github Pages deploy，you can ues jsdelivr settings
#
# jsdelivr:
#   jsdelivr_url: https://cdn.jsdelivr.net/gh/
#   github_username: V-Vincen


# Custom Setting Start

# Site settings
SEOTitle: Bin's Blog
email: bin.cs@foxmail.com
description: "It's an IT blog..."
keyword: "Bin's Blog"
header-img: img/header_img/newhome_bg.jpg
archives-img: img/header_img/archive_bg2.jpg

# Favicon settings
favicon: img/avatar/Bin.jpg

# Signature Setup
signature: false # show signature
signature-img: 


# Wave settings
wave: true


# SNS Settings
# RSS: true
github_username: lhb7
# twitter_username: V_Vincen_
# instagram_username: v_vincen_
# facebook_username:  yourAccount
# linkedin_username:  yourAccount
zhihu_username: BinBin
Email: bin.cs@foxmail.com
# weibo_username: WVincen


# Sidebar Settings
sidebar: true   # whether or not using Sidebar.
sidebar-about-description: "他说他想成为一个有趣的人..."
sidebar-avatar: img/avatar/smile.jpg    # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- visitor   # busuanzi: https://busuanzi.ibruce.info/
- featured-tags
- short-about
- recent-posts
- friends-blog
- archive
- category


# widget behavior
## Archive
archive_type: 'monthly'
show_count: true

## Featured Tags
featured-tags: true   # whether or not using Feature-Tags
featured-condition-size: 0    # A tag will be featured if the size of it is more than this condition value

## Friends
friends: [
    {
        title: "Soptq",
        href: "https://soptq.me/"
        },{
        title: "Bean Tech",
        href: "http://beantech.org"
    }
]


# Comment Settings

## Gitalk Settings
## Doc:https://github.com/gitalk/gitalk/blob/master/readme-cn.md
##
gitalk:
  enable: true
  owner: lhb7                        # 'GitHub repo owner'
  admin: lhb7                      # 'GitHub repo'
  repo: lhb7.github.io                      # ['GitHub repo owner and collaborators, only these guys can initialize github issues']
  clientID: 65682c9d7fede4bb7fc5                   # 'GitHub Application Client ID'
  clientSecret: 6b9080be7fdcaae6ae9bbd667c4d2af5f16eb118                  # 'GitHub Application Client Secret'
  labels: 'gitalk'
  perPage: 10                     # Pagination size, with maximum 100.
  pagerDirection: last            # Comment sorting direction, available values are last and first.
  createIssueManually: true      # By default, Gitalk will create a corresponding github issue for your every single page automatically when the logined user is belong to the admin users. You can create it manually by setting this option to true
  language: zh-CN                    # Localization language key, en, zh-CN and zh-TW are currently available.
  maxCommentHeight: 250           # An optional number to limit comments' max height, over which comments will be folded.Default 250.

## Gitment Settings
## Doc:https://github.com/imsun/gitment
##
# gitment:
  # enable: true
  # owner: lhb7                         # Your GitHub ID. Required.
  # repo: blogtalk                          # The repository to store your comments. Make sure you're repo's owner. Required.
  # client_id: 47449117adf283633d35                     # GitHub client ID. Required.
  # client_secret: f5275312be0c3608b0071c893654b9c911282fe1                 # GitHub client secret. Required.
  # desc:                           # An optional description for your page, used in issue's body. Default ''.
  # perPage: 10                     # An optional number to which comments will be paginated. Default 20.
  # maxCommentHeight: 250           # An optional number to limit comments' max height, over which comments will be folded. Default 250.

## Disqus settings
##
# disqus_username: your-disqus-ID


# Analytics settings

## Google Analytics
ga_track_id: UA-xxxxxx-xx   # Format: UA-xxxxxx-xx

## Baidu Analytics
ba_track_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

## Sitemap
sitemap:
  path: sitemap.xml

## Baidusitemap
baidusitemap:
    path: baidusitemap.xml

baidu_push: true

# Custom Setting End


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:


# Writing
new_post_name: :title.md    # File name of new posts
default_layout: post
auto_spacing: true
titlecase: false    # Transform title into titlecase
external_link: true   # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:


# Category & Tag
default_category: uncategorized
category_map:
tag_map:
home_posts_tag: true    # show posts tags


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
##
date_format: YYYY-MM-DD
time_format: HH:mm:ss


# Pagination
## Set per_page to 0 to disable pagination
##
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false


# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
##
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-emoji  # add emoji
  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: ¶


# Build Settings
anchorjs: true    # if you want to customize anchor. check out line:26 of `anchorjs.ejs`


# article top
top: true


# WordCount Settings
## Dependencies: https://github.com/willin/hexo-wordcount
## Docs: https://www.npmjs.com/package/hexo-wordcount
##
wordcount: true


# top scroll progress
scroll: true


# Tip
tip:
  enable: true
  copyright: If you like this blog or find it useful for you, you are welcome to comment on it. You are also welcome to share this blog, so that more people can participate in it. If the images used in the blog infringe your copyright, please contact the author to delete them. Thank you !


# Social Share Post
## Docs:https://github.com/overtrue/share.js
##
socialshare: true


# Viewer config
## Docs:https://github.com/fengyuanchen/viewer
## Demo:https://fengyuanchen.github.io/viewer/
##
viewer: true


# ThemeColor config
themecolor:
  enable: true
  mode: light # themecolor mode light or dark, default light


# Mouseclick config
mouseclick:
  enable: true
  content:
    - The first step is as good as half over...
    - Laugh and grow fat...
    - Man proposes God disposes...
    - When all else is lost the future still remains...
    - Wasting time is robbing oneself...
    - Sharp tools make good work...
    - Cease to struggle and you cease to live...
    - A friend in need is a friend indeed...
    - Faith can move mountains...
  color:
    - '#9933CC'
    - '#339933'
    - '#66CCCC'
    - '#FF99CC'
    - '#CCCCFF'
    - '#6666CC'
    - '#663399'
    - '#66CC99'
    - '#FF0033'


# Ribbon config
ribbonDynamic: true


# Line config
bglinecanvas: false  # The special effects will take up a lot of cpu resorces, please open it carefully.


# Search Setting
## Search: https://go.kieran.top/post/45/
## Dependencies: https://github.com/V-Vincen/hexo-generator-zip-search
##
search:
  path: search.json
  zipPath: search.flv
  versionPath: searchVersion.json
  field: post
  trigger: auto   # if 'auto', trigger search by changing input;if 'manual', trigger search by pressing enter key or search button
  top_n_per_article: 1    # show top n results per article, show all results by setting to -1


# Theme config
## Themes: https://hexo.io/themes/
##
theme: livemylife

 
mathjax:
    enable: true
# Gitter
## Docs:https://gitter.im/?utm_source=left-menu-logo
##
gitter:
  room: your-community/your-room


# Deployment
## Docs: https://hexo.io/docs/deployment.html
##
deploy:
  type: git
  repo: git@github.com:lhb7/lhb7.github.io.git
  branch: master
